Django/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include

from code_challenge.views import ResultsView

urlpatterns = [
    re_path(r'^$', ResultsView.as_view(), name='/'),
    re_path(r'^code_challenge/', include('code_challenge.urls')),
    path('admin/', admin.site.urls),
]

code_challenge/urls.py
from django.urls import include, path, re_path

from clients.views import AddClientView
from code_challenge import views
from rest_framework import routers

# template tagging
app_name = 'code_challenge'

router = routers.DefaultRouter()
router.register(r'sync_logs', views.SyncLogViewSet)

urlpatterns = [
    re_path(r'^$', views.ResultsView.as_view(), name='index'),
    path('add_client', AddClientView.as_view(), name='add_client'),
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

clients/models.py
from django.db.models import CharField, IntegerField
from model_utils.models import TimeStampedModel


class Client(TimeStampedModel):
    account_id = IntegerField(unique=True, db_index=True)
    one_to_fifteen_slot = IntegerField(null=True, blank=True)

scheduler/models.py
# Create your models here.

tracking/models.py
from django.db.models import IntegerField, DateTimeField
from model_utils.models import TimeStampedModel


class SyncLog(TimeStampedModel):
    account_id = IntegerField()
    sync_time = DateTimeField()

clients/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.views.generic import CreateView

from clients.models import Client


class AddClientView(CreateView):
    model = Client
    fields = ['account_id']
    template_name = 'code_challenge/add_client.html'
    success_url = 'add_client'

    def form_valid(self, form, **kwargs):
        data = form.cleaned_data
        account_id = data['account_id']
        try:
            last_created_client = Client.objects.latest('id')
            # print('last_created_client: {}'.format(last_created_client))
            last_created_client_one_to_fifteen = last_created_client.one_to_fifteen_slot
            if last_created_client_one_to_fifteen >= 15:
                form.instance.one_to_fifteen_slot = 1
            else:
                form.instance.one_to_fifteen_slot = last_created_client_one_to_fifteen + 1
        except ObjectDoesNotExist as ex:
            print(ex)
            form.instance.one_to_fifteen_slot = 1
        print('Creating new client with account_id: {0}, one_to_fifteen_slot: {1}'.format(account_id, form.instance.one_to_fifteen_slot))
        form.save()
        context = self.get_context_data(**kwargs)
        context['status'] = 'Created new client with account_id: {0}, one_to_fifteen_slot: {1}'.format(account_id, form.instance.one_to_fifteen_slot)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(AddClientView, self).get_context_data(**kwargs)
        return context

code_challenge/views.py
from django.views.generic import ListView
from rest_framework import viewsets

from code_challenge.serializers import SyncSerializer
from tracking.models import SyncLog


class ResultsView(ListView):
    context_object_name = 'sync_logs'
    model = SyncLog
    ordering = ['-modified']
    template_name = 'code_challenge/results.html'

    def __init__(self):
        super().__init__()
        self.object_list = self.model.objects.all()

    def get_queryset(self):
        sync_logs = SyncLog.objects.all().order_by('-modified')[:1000]
        return sync_logs


class SyncLogViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows Sync Logs to be viewed.
    """
    queryset = SyncLog.objects.all().order_by('-modified')
    serializer_class = SyncSerializer

scheduler/views.py
# Create your views here.

tracking/views.py
# Create your views here.

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href={% static "/bootstrap-5.0.2-dist/css/bootstrap.min.css" %}>
<!-- Latest compiled and minified JavaScript -->
<script src={% static "/bootstrap-5.0.2-dist/js/bootstrap.min.js" %}></script>

<html>
<head>
    <meta charset="utf-8">
    <meta charset="UTF-8">
    <title>Code Challenge</title>
</head>
<body>
    <div style="padding-top:1rem;">
        <nav class="left" style="padding-left:3rem">
            <a class="left_nav_item" href="{% url 'code_challenge:index' %}">Sync Logs</a>
            <a class="left_nav_item" style="padding-left: 3rem" href="{% url 'code_challenge:add_client' %}">Add New Client</a>
        </nav>
    </div>

    <div class="container">
        {% block body_block %}
        <!-- Anything outside of this will be inherited if you extend -->
        {% endblock %}
    </div>

</body>
</html>

templates/code_challenge/add_client.html
<!DOCTYPE html>
{% extends "code_challenge/../base.html" %}
{% load custom_tags %}

    {% block body_block %}
        <h4 style="padding-top: 2rem">Add the account id number you want to use for the new client:</h4>

        <form method="post">{% csrf_token %}
            <div align="left" style="margin:20px">
                {% for field in form %}
                    <div class="form-group row mt-3">
                      <div class="col-sm-2 col-form-label">
                        {{ field.label_tag }}
                        {% if field.help_text %}
                          <sup>{{ field.help_text }}</sup>
                        {% endif %}
                        {% for error in field.errors %}
                           <div class="row">
                             <div class="alert alert-danger">{{error}}</div>
                           </div>
                        {% endfor %}
                       </div>
                        <div class="form-group col-sm-3">
                         {{ field|add_css:"form-control" }}
                       </div>
                    </div>
                  {% endfor %}
                <button class="btn btn-lg btn-outline-primary" type="submit">Save New Client</button>
            </div>
        </form>
        {% if status %}
            <span style="color: red">{{ status }}</span>
            <br>
        {% endif %}

    {% endblock %}

templates/code_challenge/results.html
<!DOCTYPE html>

{% extends "code_challenge/../base.html" %}
    {% block body_block %}
        <head>
            <meta http-equiv="refresh" content="60">
        </head>
        <h3>{{ title }}</h3>

        <h4>Here are your most recent client synchronizations (this page refreshes every minute):</h4>

        {% if sync_logs %}
        <table class = "table table-dark">
            <thead class="thead-inverse">
                <th>Client</th>
                <th>Sync Time</th>
            </thead>

        {% for log in sync_logs %}
        <tr>
            <td>{{ log.account_id }}</td>
            <td>{{ log.sync_time }}</td>
        </tr>
        {% endfor %}

        </table>
        {% else %}
            <p>No records found!</p>

        {% endif %}<br><br>

    {% endblock %}